class Favorite {
  String gambar;
  String judul;
  String penulis;
  List bahan;
  List langkah;
  String deskripsi;
  String kalori;
  String porsi;
  String durasi;
  String level;

  Favorite({
    this.gambar,
    this.judul,
    this.penulis,
    this.deskripsi,
    this.bahan,
    this.langkah,
    this.kalori,
    this.porsi,
    this.durasi,
    this.level,
  });
}

final favorites = [
  Favorite(
    gambar: 'assets/images/food1.jpg',
    judul: 'Kepiting Soka',
    penulis: 'Tegar Yasindra',
    deskripsi:
        'Resep Kepiting Soka Goreng Tepung Renyah Crispy Asli Enak. Bagi pecinta makanan seafood pasti sudah sering makan masakan kepiting hidangan internasional ini, memang dari banyaknya aneka olahan kepiting soka ini paling enak masak goreng tepung garing atau dimasak dengan saus tomat atau saus sambal, seperti masak saus lada hitam, saus telur asin, saus padang, saus asam manis, saus asam pedas, saus tiram, dll',
    bahan: [
      '4 ekor kepiting soka',
      '4 siung bawang putih',
      '100 gram tepung terigu',
      '50 gram tepung maizena',
      '1 sendok teh merica bubuk',
      '2 butir telur, kocok lepas',
      'Garam secukupnya',
      'Minyak goreng secukupnya',
    ],
    langkah: [
      'Cuci terlebih dahulu kepiting soka, bersihkan dan buang bagian insangnya. Potong kepiting soka menjadi beberapa bagia kemudian sisihkan.',
      'Campurkan terlebih dahulu beberapa bahan seperti bawang putih, tepung terigu maizena, merica serta garam, kemudia aduk hingga merata.',
      'Ambil kepiting kemudian celupkan ke dalam telur, setelah itu lanjutkan dengan menggulingkan ke dalam campuran tepung terigu hingga merata.',
      'Setelah semua kepiting tercampur dengan merata lanjutkan dengan menggoreng dalam minyak panas. Pastikan kepiting tersebut anda goreng sampai matang dan berwarna kecokelatan.',
      'Setelah matang kemudian angkat dan tiriskan.',
      '2 Butir Telur, Kocok Lepas',
      'Sajikan bersama dengan saus sambal atau lemon sesuai dengan selera anda masing-masing.',
    ],
    kalori: '310',
    porsi: '4',
    durasi: '60',
    level: 'Hard',
  ),
  Favorite(
    gambar: 'assets/images/food2.jpg',
    judul: 'Soto Banjar',
    penulis: 'Tegar Yasindra',
    deskripsi:
        'Resep Kepiting Soka Goreng Tepung Renyah Crispy Asli Enak. Bagi pecinta makanan seafood pasti sudah sering makan masakan kepiting hidangan internasional ini, memang dari banyaknya aneka olahan kepiting soka ini paling enak masak goreng tepung garing atau dimasak dengan saus tomat atau saus sambal, seperti masak saus lada hitam, saus telur asin, saus padang, saus asam manis, saus asam pedas, saus tiram, dll',
    bahan: [
      '4 Ekor kepiting soka',
      '4 Siung bawang putih',
      '100 gram tepung terigu',
      '50 gram tepung maizena',
      '1 sendok teh merica bubuk',
      '2 butir telur, kocok lepas',
      'Garam secukupnya',
      'Minyak goreng secukupnya',
    ],
    langkah: [
      'Cuci terlebih dahulu kepiting soka, bersihkan dan buang bagian insangnya. Potong kepiting soka menjadi beberapa bagia kemudian sisihkan.',
      'Campurkan terlebih dahulu beberapa bahan seperti bawang putih, tepung terigu maizena, merica serta garam, kemudia aduk hingga merata.',
      'Ambil kepiting kemudian celupkan ke dalam telur, setelah itu lanjutkan dengan menggulingkan ke dalam campuran tepung terigu hingga merata.',
      'Setelah semua kepiting tercampur dengan merata lanjutkan dengan menggoreng dalam minyak panas. Pastikan kepiting tersebut anda goreng sampai matang dan berwarna kecokelatan.',
      'Setelah matang kemudian angkat dan tiriskan.',
      '2 Butir Telur, Kocok Lepas',
      'Sajikan bersama dengan saus sambal atau lemon sesuai dengan selera anda masing-masing.',
    ],
    kalori: '310',
    porsi: '4',
    durasi: '60',
    level: 'Medium',
  ),
  Favorite(
    gambar: 'assets/images/food3.jpg',
    judul: 'Ketupat Kandangan',
    penulis: 'Yuliana Dwianti',
    deskripsi:
        'Resep Kepiting Soka Goreng Tepung Renyah Crispy Asli Enak. Bagi pecinta makanan seafood pasti sudah sering makan masakan kepiting hidangan internasional ini, memang dari banyaknya aneka olahan kepiting soka ini paling enak masak goreng tepung garing atau dimasak dengan saus tomat atau saus sambal, seperti masak saus lada hitam, saus telur asin, saus padang, saus asam manis, saus asam pedas, saus tiram, dll',
    bahan: [
      '15 urung/ selongsong ketupat',
      '1 cup beras, cuci bersih, tirikan',
      '1/2 kg kelapa parut, peras airnya',
      '1 ekor ikan haruan besar, potong & diasap',
      '1 sendok teh merica bubuk',
      '1 butir telur ayam, kocok lepas',
      '2 sdt Royco rasa ayam',
      '8 siung bawang merah',
      '3 siung bawang putih',
      '3 cm lengkuas',
      '3.5 cm kencur',
      '2 cm jahe',
      '2 batang sereh, ambil putihnya',
      '6 biji kemiri',
      '10 buah cabe rawit',
      '2 sdm kuah santan ketupat',
      '1-2 siung bawang merah bakar',
      '2 buah jeruk limau/ buah binjai',
      'Sejumput garam',
    ],
    langkah: [
      'Masukan beras kedalam urung ketupat kurleb isian berasnya setengah (sedang), isian beras 3/4 ketupat agak padat dan nanti kalo disantap akan seperti nasi, dan kalau dimakan biasanya diremas pake tangan.',
      'Rebus air hingga mendidih, masukan ketupat, masak kurang lebih 20 menit hingga urung ketupat berubah warnanya dari hijau menjadi kuning kecoklatan, tekstur ketupat sudah keras dan padat. ',
      'Angkat dan tiriskan,memasak ketupatnya ga perlu lama seperti bikin ketupat soto (3 jam),cukup 20 menit aja.',
      'Peras santan kurleb 1500 ml, campurkan bumbu halus, kocokan telur, ikan asap, garam, masak hingga mendidih sambil diaduk agar santan tidak pecah, tambahkan royco dan tes rasa sesuai selera, matikan api.',
      'Sambal : Bakar bawang merah dan kupas. Kemudian ulek cabe rawit, garam, bawang merah bakar, sedikit buah binjai atau buah binjai diganti perasan jeruk limau dan tambahkan sedikit kuah santannya.',
      'Ketupat Kandangan siap dinikmati.',
    ],
    kalori: '240',
    porsi: '2',
    durasi: '83',
    level: 'Easy',
  ),
  Favorite(
    gambar: 'assets/images/food4.png',
    judul: 'Chai Kue',
    penulis: 'Katto',
    deskripsi:
        'Resep Kepiting Soka Goreng Tepung Renyah Crispy Asli Enak. Bagi pecinta makanan seafood pasti sudah sering makan masakan kepiting hidangan internasional ini, memang dari banyaknya aneka olahan kepiting soka ini paling enak masak goreng tepung garing atau dimasak dengan saus tomat atau saus sambal, seperti masak saus lada hitam, saus telur asin, saus padang, saus asam manis, saus asam pedas, saus tiram, dll',
    bahan: [
      '210 gram tepung beras',
      '60 gram tepung tapioka atau tepung sagu',
      '360 ml air mendidih',
      '1/4 sendok teh garam beryodium',
      '2 sendok the minyak sayur',
      '5 buah cabai rawit',
      '7 siung bawang putih dan cincang sampai halus',
      '400 gram bengkoang',
      '60 gram udang ebi',
      'Gula secukupnya',
      '3.5 cm kencur',
      '2 cm jahe',
      '2 batang sereh, ambil putihnya',
      '6 biji kemiri',
      '10 buah cabe rawit',
      '2 sdm kuah santan ketupat',
      '1-2 siung bawang merah bakar',
      '2 buah jeruk limau/ buah binjai',
      'Sejumput garam',
    ],
    langkah: [
      'Pastikan semua bahan yang sudah dijelaskan sudah siap.',
      'Tumis seluruh bawang putih bersama ebi sampai mengeluarkan bau harum. Setelah itu masukkan bengkoang dan beri sedikit air supaya tidak gosong.',
      'Beri gula dan garam sambil terus diaduk.',
      'Masukkan bengkoang dan masak sampai warna berubah kecoklatan.',
      'Sekarang saatnya membuat bagian kulit dengan memasukkan tepung beras, tepung sagu dan garam ke dalam suatu wadah. Selanjutnya masukkan air mendidih secara perlahan dan aduk menggunakan sendok sayur. Masukkan minyak sayur dan kembali aduk supaya merata.',
      'Jika sudah merata, maka sisihkan adonan tadi ke dalam panci untuk dipanaskan.',
      'Nyalakan kompor dengan api kecil dan aduk terus secara perlahan sampai adonan berubah teksturnya menjadi kental.',
      'Matikan kompor dan biarkan adonan sedikit mendingin dahulu sebelum diuleni.',
      'Tuang adonan kental dari campuran tepung tadi di atas telenan dan uleni sampai kalis.',
      'Kemudian ambil sedikit adonan dan dibuat pipih. Isi dengan bengkuang secukupnya supaya bisa ditutup dengan adonan seluruh isinya. Tutup isi bengkoang. Ulangi seluruh langkah ini sampai adonan habis.',
      'Selanjutnya kamu bisa menyiapkan alat kukusan sambil dipanasi dahulu. Paling tidak tahapan ini terjadi selama 10 menit agar panasnya merata.',
      'Masukkan seluruh adonan berisi bengkuang dan biarkan kembali selama 10 menit.',
      'Apabila kukusan sudah matang, kamu bisa menambahkan topping-nya dengan bawang goreng.',
    ],
    kalori: '216',
    porsi: '2',
    durasi: '90',
    level: 'Medium',
  ),
];
